version: '3'
services:
    app:
        container_name: docker-node-mongo
        restart: always
        # build from dockerfile - look in current directory
        build: .
        ports:
            - '80:3000'
        # link app container to mongo container    
        links:
            - mongo 
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - '27017:27017'
